import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex items-center justify-between p-4 bg-green-500 black'>
        <h1>Cookie Stand Admin</h1>
      </header>
      <main>
        <aside>
          <form className="flex w-3/4 p-6 mx-auto my-6  bg-green-500">
            <fieldset>
              <legend className='content-center w-1/4 mx-auto my-4 bg-green-500'>Create Cookie Stand</legend>
              <label className='content-center w-1/4 mx-auto my '>Location
                <input className='content-center mx-2 my-2 w-10/12' type="text" name="location" placeholder=" ex: Rome" required />
              </label>
              <div className="flex justify-around w-5/5">
                <label className='justify-between p-2 flex flex-col'>Min Customers per Hour
                  <input className='mx-2 my-2' type="number" name="min" required />
                </label>
                <label className='justify-between p-2 flex flex-col'>Max Customers per Hour
                  <input className='mx-2 my-2' type="number" name="max" required />
                </label>
                <label className='justify-between p-2 flex flex-col'>Avg Cookies per Customer
                  <input className='mx-2 my-2' type="number" name="avg" required />
                </label>
                <button className="inline-grid text-center w-48 mx-2 my-2 px-6 py-4 bg-gray-700 text-gray-50 ">Create</button>
              </div>
            </fieldset>
          </form>
        </aside>
      </main>
      <footer className='p-4 mt-8  bg-green-500 black'>
        <p> &copy Angelos Kounavis 2023 </p>
      </footer>
    </>
  )
}